MEMBER_NAME = ''
ROOM_ID = 0
MEMBER_ID = 0

AUTO_REPLY_GROUPS = []
MEMBER_ROOM_MSG_GROUPS = []
MEMBER_ROOM_COMMENT_GROUPS = []
MEMBER_WEIBO_GROUPS = []
MEMBER_LIVE_GROUPS = []
MEMBER_ROOM_MSG_LITE_GROUPS = []
JIZI_NOTIFY_GROUPS = []

# 集资
JIZI_KEYWORDS = []
JIZI_LINK = []

WEIBO_KEYWORDS = []
WEIBO_LINK = ''
SUPER_TAG = ''

GONGYAN_KEYWORDS = []
LIVE_LINK = []
LIVE_SCHEDULE = []

MEMBER_ATTR = ''
I_LOVE = []

AT_AUTO_REPLY = []
ROOM_MSG_LITE_NOTIFY = ''

# 公演直播提醒
PERFORMANCE_NOTIFY = ''

# 微打赏
WDS_LINK = ''
WDS_TITLE = ''
WDS_MOXI_ID = ''
WDS_PRO_ID = ''
