MEMBER_NAME = ''
ROOM_ID = 0
MEMBER_ID = 0

AUTO_REPLY_GROUPS = []
MEMBER_ROOM_MSG_GROUPS = []
MEMBER_ROOM_COMMENT_GROUPS = []
MEMBER_WEIBO_GROUPS = []
MEMBER_LIVE_GROUPS = []

JIZI_KEYWORDS = []
JIZI_LINK = []

WEIBO_KEYWORDS = []
WEIBO_LINK = ''
SUPER_TAG = ''

GONGYAN_KEYWORDS = []
LIVE_LINK = []
LIVE_SCHEDULE = []

MEMBER_ATTR = ''
I_LOVE = []

AT_AUTO_REPLY = []
